# Generated by Django 4.0.5 on 2022-07-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_is_mine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_exposure',
            field=models.BooleanField(verbose_name='노출여부'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_mine',
            field=models.BooleanField(verbose_name='소유여부'),
        ),
        migrations.AlterField(
            model_name='post',
            name='on_sale',
            field=models.BooleanField(default=True, verbose_name='판매여부'),
        ),
    ]
